# Word Embedding Techniques using Embedding Layer in Kera

In [2]:
!pip install tensorflow

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
### Vocabulary size
voc_size=10000

# One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4477, 3096, 8708, 7428], [4477, 3096, 8708, 1148], [4477, 9171, 8708, 7056], [6307, 3955, 6526, 9654, 7080], [6307, 3955, 6526, 9654, 3118], [3787, 4477, 8402, 8708, 891], [8810, 5705, 2601, 9654]]


# Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4477 3096 8708 7428]
 [   0    0    0    0 4477 3096 8708 1148]
 [   0    0    0    0 4477 9171 8708 7056]
 [   0    0    0 6307 3955 6526 9654 7080]
 [   0    0    0 6307 3955 6526 9654 3118]
 [   0    0    0 3787 4477 8402 8708  891]
 [   0    0    0    0 8810 5705 2601 9654]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 110ms/step
[[[-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387
   -0.01504936  0.01799805 -0.01783764  0.0386925  -0.04322822]
  [-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387
   -0.01504936  0.01799805 -0.01783764  0.0386925  -0.04322822]
  [-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387
   -0.01504936  0.01799805 -0.01783764  0.0386925  -0.04322822]
  [-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387
   -0.01504936  0.01799805 -0.01783764  0.0386925  -0.04322822]
  [ 0.00137594  0.00276637  0.04149084 -0.04060443 -0.02817479
   -0.03922925 -0.02817236 -0.0358298  -0.00444137 -0.04174248]
  [ 0.04141381 -0.00697771 -0.01440216 -0.02702695  0.01449532
    0.02296988 -0.02411766 -0.03215828  0.04425937 -0.0319946 ]
  [ 0.0494304   0.01630464 -0.02575197 -0.00919491  0.04662343
    0.00626554 -0.03902562  0.03494407 -0.02589599 -0.02032065]
  [-0.04199982 -0.01854406  0.02419862 -0.04923437 -0.0095

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 4477, 3096, 8708, 7428])

In [16]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 20ms/step
[[-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387 -0.01504936
   0.01799805 -0.01783764  0.0386925  -0.04322822]
 [-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387 -0.01504936
   0.01799805 -0.01783764  0.0386925  -0.04322822]
 [-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387 -0.01504936
   0.01799805 -0.01783764  0.0386925  -0.04322822]
 [-0.03442298 -0.04411849 -0.02407839 -0.04123946  0.03186387 -0.01504936
   0.01799805 -0.01783764  0.0386925  -0.04322822]
 [ 0.00137594  0.00276637  0.04149084 -0.04060443 -0.02817479 -0.03922925
  -0.02817236 -0.0358298  -0.00444137 -0.04174248]
 [ 0.04141381 -0.00697771 -0.01440216 -0.02702695  0.01449532  0.02296988
  -0.02411766 -0.03215828  0.04425937 -0.0319946 ]
 [ 0.0494304   0.01630464 -0.02575197 -0.00919491  0.04662343  0.00626554
  -0.03902562  0.03494407 -0.02589599 -0.02032065]
 [-0.04199982 -0.01854406  0.02419862 -0.04923437 -0.00951967  0.01343505